# Generated by Django 5.0.6 on 2026-03-12 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('technology', 'Teknologi'), ('business', 'Bisnis'), ('entertainment', 'Hiburan'), ('sports', 'Olahraga'), ('politics', 'Politik'), ('science', 'Sains'), ('health', 'Kesehatan'), ('general', 'Umum')], default='general', max_length=50)),
                ('source', models.CharField(choices=[('google_trends', 'Google Trends'), ('news_api', 'News API'), ('combined', 'Gabungan')], default='google_trends', max_length=50)),
                ('current_interest', models.FloatField(default=0.0, help_text='0-100 scale from Google Trends')),
                ('peak_interest', models.FloatField(default=0.0)),
                ('growth_rate', models.FloatField(default=0.0, help_text='Percentage growth in last 24h')),
                ('is_active', models.BooleanField(default=True)),
                ('is_breaking', models.BooleanField(default=False, help_text='Sudden spike detected')),
                ('first_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topik Tren',
                'verbose_name_plural': 'Topik-Topik Tren',
                'ordering': ['-current_interest', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source_name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('sentiment_score', models.FloatField(default=0.0, help_text='-1 negative, 0 neutral, 1 positive')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='trends.trendtopic')),
            ],
            options={
                'verbose_name': 'Artikel Berita',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('interest_value', models.FloatField(help_text='Interest value 0-100')),
                ('news_count', models.IntegerField(default=0, help_text='Number of news articles at this time')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='trends.trendtopic')),
            ],
            options={
                'verbose_name': 'Data Point Tren',
                'ordering': ['timestamp'],
                'unique_together': {('topic', 'timestamp')},
            },
        ),
    ]
