# Generated by Django 5.0.6 on 2026-03-12 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_7d', models.JSONField(default=list, help_text='7-day forecast: [{date, value, lower, upper}]')),
                ('forecast_30d', models.JSONField(default=list, help_text='30-day forecast')),
                ('predicted_peak', models.FloatField(default=0.0)),
                ('predicted_peak_date', models.DateTimeField(blank=True, null=True)),
                ('trend_direction', models.CharField(choices=[('rising', 'Naik'), ('stable', 'Stabil'), ('declining', 'Turun'), ('volatile', 'Volatile')], default='stable', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Model confidence 0-1')),
                ('model_type', models.CharField(default='prophet', max_length=50)),
                ('training_data_points', models.IntegerField(default=0)),
                ('mae', models.FloatField(default=0.0, help_text='Mean Absolute Error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='trends.trendtopic')),
            ],
            options={
                'verbose_name': 'Prediksi ML',
                'ordering': ['-created_at'],
            },
        ),
    ]
