# Generated by Django 5.0.6 on 2026-03-12 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViralityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('search_volume_score', models.FloatField(default=0.0, help_text='Based on raw search interest')),
                ('growth_velocity_score', models.FloatField(default=0.0, help_text='Speed of growth')),
                ('news_coverage_score', models.FloatField(default=0.0, help_text='News article coverage')),
                ('momentum_score', models.FloatField(default=0.0, help_text='Sustained growth momentum')),
                ('tier', models.CharField(choices=[('mega', 'Mega Viral (90-100)'), ('high', 'Sangat Viral (70-89)'), ('medium', 'Viral (50-69)'), ('low', 'Mulai Viral (30-49)'), ('minimal', 'Belum Viral (0-29)')], default='minimal', max_length=20)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virality_scores', to='trends.trendtopic')),
            ],
            options={
                'verbose_name': 'Skor Viralitas',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
