# Generated by Django 5.0.6 on 2026-03-12 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_trending', models.TextField(help_text='AI explanation of why this is trending')),
                ('potential_impact', models.TextField(help_text='Potential impact analysis')),
                ('target_audience', models.TextField(blank=True)),
                ('predicted_longevity', models.CharField(choices=[('hours', 'Beberapa Jam'), ('days', 'Beberapa Hari'), ('weeks', 'Beberapa Minggu'), ('months', 'Beberapa Bulan'), ('permanent', 'Jangka Panjang')], default='days', max_length=50)),
                ('overall_sentiment', models.CharField(choices=[('positive', 'Positif'), ('neutral', 'Netral'), ('negative', 'Negatif')], default='neutral', max_length=20)),
                ('model_used', models.CharField(default='llama3-70b-8192', max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='trends.trendtopic')),
            ],
            options={
                'verbose_name': 'Wawasan AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('blog', 'Blog/Artikel'), ('business', 'Peluang Bisnis'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('hooks', models.JSONField(default=list, help_text='List of attention hooks/angles')),
                ('estimated_reach', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Mudah'), ('medium', 'Sedang'), ('hard', 'Sulit')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ideas', to='trends.trendtopic')),
            ],
            options={
                'verbose_name': 'Ide Konten',
                'ordering': ['platform', '-created_at'],
            },
        ),
    ]
